package com.example.a11699.androidxallstudy

import  kotlinx.coroutines.flow.Flow
import com.hapi.datasource.BaseReposity
import com.hapi.datasource.FlowDataFetcher
import kotlin.Unit

/**
 * This file is generated by kapt, please do not edit this file */
open class LoginReposity : BaseReposity<LoginService>() {
    fun login(): Flow<Unit> {
         return FlowDataFetcher{ 
                 apiService.login() 
                }.startFetchData()
    }
}
